Arrays como vectores y matrices

In [ ]:
import numpy as np

In [ ]:
#Array de un dimensión (vector)
a=np.array([1,2,3])

#Array de dos dimensiones (matriz)
b=np.array([[1,2,3], [4,5,6]])



In [ ]:
a,b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b) #Aquí ambos son vectores 1D, así que NumPy hace un producto escalar (dot product)
            #Resultado: un número (1x4 + 2x5 + 3x6 =32 )

np.int64(32)

In [ ]:
A=np.array([[2,4,6],[4,5,7],[6,7,9]])
B=np.array([[1,2,3],[0,1,4],[5,6,0]])
A,B

(array([[2, 4, 6],
        [4, 5, 7],
        [6, 7, 9]]),
 array([[1, 2, 3],
        [0, 1, 4],
        [5, 6, 0]]))

In [ ]:
producto=np.dot(A,B)
print(producto)

[[32 44 22]
 [39 55 32]
 [51 73 46]]


Suma/resta de matrices

In [ ]:
C=A+B
C

array([[ 3,  6,  9],
       [ 4,  6, 11],
       [11, 13,  9]])

In [ ]:
A.T

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.array_equal(A,A.T) #Compara elemento por elemento si todos los valores coinciden, devuelve True. #Si al menos uno es diferente, devulve False.


True

Determinante

In [ ]:
np.linalg.det(A)

np.float64(3.9999999999999867)

Inversa de una matriz

In [ ]:
B_i=np.linalg.inv(B) #Inversa de una matriz
B_i

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [ ]:
A=np.array([[2,4,6,],[4,5,7],[6,7,9]])
A

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.mean(A)

np.float64(5.555555555555555)

In [ ]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

Sistema de ecuaciones

1. Identifica la matriz de coeficientes (A)

In [ ]:
import numpy as np

In [ ]:
A=np.array([[2,4,6],[4,5,6],[3,1,-2]])

2. Calcula el determinante principal (D o det(A))

In [ ]:
D=np.linalg.det(A)
D

np.float64(5.999999999999996)

3. Crea matrices modificadas para cada variable


*   Para encontrar X:reemplaza la primeta columna de A con el vector de términos independientes.
*   Para encontrar Y: reemplaza la segunda columna
Para encontrar Z: reemplaza la tercera columan (y así sucesivamente)



In [ ]:
x=np.array([[18,4,6],[24,5,6],[4,1,-2]])

4. Calcula el determinante de cada matriz modificada
Dx, Dy, Dz, etc.

In [ ]:
Dx=np.linalg.det(x)
Dx

np.float64(24.000000000000004)

5. Aplica la fórmula Cramer
x=Dx/D
y=Dy/D
z=Dz/D

In [ ]:
x=Dx/D
x

np.float64(4.0000000000000036)

In [ ]:
b=np.array([18,24,4]) #Comprobación

x=np.linalg.solve(A,b)
x

array([ 4., -2.,  3.])

In [ ]:
np.dot(A,x)

array([18., 24.,  4.])